### PR TITLE
N5Volume

### PR DESCRIPTION
**Pull request by pattonw**
Added support for an N5 volume. Also added a test for the N5 volume.

Relies on pyn5 which has been added to the dependency list

### CODE REVIEW

**Comment by pattonw** [comment]
This feature won't pass the python 2.7 and 3.4 tests since it relies on pyn5 which isn't available on either of them. Maybe N5Volume should be put behind a feature flag or something. Not sure what the best way to do that is.

**Comment by aschampion** [comment]
We're dropping Python 2 support and I'm also fine with dropping 3.4 as its end of life release is later this month. We should add 3.7 to build matrix/tox, though.

**Comment by pattonw** [comment]
Hmm, it looks like there's issues with the tensorflow version in python 3.7

**Comment by aschampion** [comment]
Ugh, I forgot TensorFlow didn't support python 3.7 until version 1.13. I'm not ready to update diluvian that far yet and will do so in a separate PR.

For now amend the branch to not add 3.7.

**Comment by pattonw** [comment]
Sounds good. I removed python 3.7 and squashed the commits down. Should I start a pull request with the travis/tox changes in another branch and make a note that tensorflow needs to be upgraded so we don't forget?

**Comment by aschampion** [comment]
> Should I start a pull request with the travis/tox changes in another branch and make a note that tensorflow needs to be upgraded so we don't forget?

Sounds good. This PR looks good, so merging.

**Pull request merged**
